# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kdm', '0003_auto_20160531_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='publish',
        ),
    ]
