# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import kdm.models


class Migration(migrations.Migration):

    dependencies = [
        ('kdm', '0004_auto_20160531_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to=kdm.models.upload_location)),
                ('publish', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
